language: node_js
sudo: false
node_js:
  - 0.10
  - 0.12
  - 4
  - 5
# NodeJS v4 requires gcc 4.8
env:
  - NODE_ENV=travis CXX="g++-4.8" CC="gcc-4.8"
matrix:
  allow_failures:
    - node_js: 5
services:
  - mongodb
# gcc 4.8 requires ubuntu-toolchain-r-test
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
    - gcc-4.8
    - clang
before_install:
  - gem update --system
  - gem install sass --version "=3.3.7"
  - npm i nsp -g
  - npm install protractor
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - 'node_modules/protractor/bin/webdriver-manager update --standalone --firefox'
  - 'node_modules/protractor/bin/webdriver-manager start 2>&1 &'
  - sleep 3
after_script:
  - nsp audit-package
  - grunt coverage
notifications:
  webhooks:
    urls:
      - $GITTER_IM_URL
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
  slack:
    rooms:
      secure: Q0+G0x+2EI5Y1SDhImks8rROZlr6Hlc0s7Ydcsotk7S9ZiT3osbSw9e3gxTNU9tvoL2xSNUWCNJio7b8QaAvlOUUD4tDBadybjaCH2Tob42Mu48vjI/mGS6/J9Qt7DjW/FOv2TZnIHJgs/O/wKcs22PPBYUVbqOL1A+sF0qq4kHN6RFg1hMDrx2+FiuSqRVllwfqwqNzFou9RRx+GN4g9JfV51ugLFY87wrPyDhg6s4i8Tk6A1E2+fhLEpFuYSzEi4+caRXe6+jYtJXehDzFQ1Hn2qrqK1ir2wYaw1bOnAq/LoxczK5DqdBgJHoyibYzpaTQlWyUu5VMjPlRvIPltatrMGVSeijoPiiZkhCOjJ0/cfmgofuL6kizpFq84csP0QYROH53wO/c84X/jc3uA0dAkjNjRi86v6EqG/jmM5NDJJzxN74NLSIsdY4ZMh3Nq7uOVUMbkxK4ltfTEYs7gW1kpRbQHylhXu4GK7fqDhnCFgToJkIO86o5zfjJNkuqtkScLHAInpPfeyvz7wfyJmRz98V3wo6HOKNeezSzEg7l77l1NDSDcPwruVU3NxmNfhjoUaNP7CVsWFzQo46x/mvcuUQhR9Hi8J9VwgWmvNHPXDpFu2Z7YM88o5iOKhW/2S79IA+wKIUhyLLJpKGHerMS0gbQ6nL/QYDqp+pioj4=
